<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2023/01/21 11:21:56

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=orangeapi',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
