<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2023/01/21 18:04:15

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql://root:anroiD741@localhost:3307/jobeet',
  'username' => 'root',
  'password' => 'anroiD741',
  'name' => 'doctrine',
)),);
